### ISSUE TITLE
[Question] Data import

### ISSUE THREAD

**Issue by myangelkamikaze** [noro6/kc-web#1]
Is it possible to import player data (fleet+AB, all ships, all equipment) from the browser console? The best I could find in console was access to the Vue store, but that doesn't look like the right way.

**Comment by noro6** [comment]
Importing player data directly from the browser console is not yet supported.
If you have an idea of what you want to do, I will consider implementing features to meet those requirements.

**Comment by myangelkamikaze** [comment]
We're currently reworking tools in 七四式.
I was thinking of using 制空権シミュレータ instead of 基地航空隊編成 because it offers a lot more features.
Importing data from the console would be convenient because you could simply open制空権シミュレータ in 七四式 and have all your data available already, instead of having to manually copy all data.

It's not a high priority feature, since importing data is already easy.

**Comment by sinsinpub** [comment]
ん？`console`の意味にみんなの理解がちょっと齟齬ありませんか？ていうか、どっちも日本語でいいじゃないｗ

現在noroさんのサイト既に`https://noro6.github.io/kc-web?predeck={}`という形でデータ導入できますが、観測儀の「デッキビルダー」の代わりになるものなら、私思うに「全艦隊と基地」のほかにただ「すべて艦娘と装備」も導入出来るように拡張が必要じゃないかと。

そこでnoroさんにしてもらいたいことですが、知っていたかもしれないが、`?predeck={}`みたいなquery parameterというのは文字列長さの制限があり、超えると`URI too long`のエラーがサーバーから発生する。URL圧縮とか手もあるが、簡単に`#predeck={}`というURL fragments（hashはURIとしてサーバーに送らない、`predeck=`もなくていい）の形に変えても制限が大分緩くなるんです(chromiumなら2MBytesまで？たぶん)。そしたら導入出来るデータの量結構増えるでしょう、ご検討して頂きたいです。

**Comment by noro6** [comment]
`https://noro6.github.io/kc-web#import:{}`の形式でインポート機能を拡張しました。https://github.com/noro6/kc-web/commit/9b647c8fd61e80ee70501f44af5830347e8a72cf

扱えるデータ型は次の通りです。
```
{
  "ships": 艦隊分析コード(艦娘),
  "items": 艦隊分析コード(装備),
  "predeck": デッキビルダー
}
```
e.g
-
[https://noro6.github.io/kc-web#import:{"ships":[{"api_ship_id":1,"api_lv":1,"api_kyouka":[0,0,0,0,0,0,0],"api_exp":[0,100,0],"api_slot_ex":0,"api_sally_area":0}],"items":[{"api_slotitem_id":1,"api_level":10}],"predeck":{"version":4,"hqlv":120,"f1":{"s1":{"id":"1","lv":1,"hp":13,"luck":12,"items":{"i1":{"id":1,"mas":0,"rf":1}}}},"a1":{"mode":1,"items":{"i1":{"id":168,"mas":7,"rf":4}}}}}](https://noro6.github.io/kc-web#import:{"ships":[{"api_ship_id":1,"api_lv":1,"api_kyouka":[0,0,0,0,0,0,0],"api_exp":[0,100,0],"api_slot_ex":0,"api_sally_area":0}],"items":[{"api_slotitem_id":1,"api_level":10}],"predeck":{"version":4,"hqlv":120,"f1":{"s1":{"id":"1","lv":1,"hp":13,"luck":12,"items":{"i1":{"id":1,"mas":0,"rf":1}}}},"a1":{"mode":1,"items":{"i1":{"id":168,"mas":7,"rf":4}}}}})

本機能によって、想定されている機能の実現は可能でしょうか。ご確認くださいませ。

**Comment by myangelkamikaze** [comment]
Tried it, and it works on Firefox, Edge and WebView2. I don't have Google Chrome installed, so I can't confirm the limitation that was described above.

Importing via URL isn't optimal, however, because it forces a full page reload and sends you back to the main page. Though I'm not sure if refreshing data will be a significant use case, and has a trivial workaround of closing the page and opening it again.

I think the feature is okay as implemented, I'll open a new issue in case refreshing the data without closing the page ever comes up.

Thank you!

**Comment by sinsinpub** [comment]
if data refreshing repeatedly needed, I guess import-data either accepting [window message event](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event) is better way, something like:
kcweb side: ```window.addListener("message", (event) => { // check event type and get json data... });```
viewer side: `wndRef = window.open(kcweb);` once,  `wndRef.postMessage(json);` on demand
this method no significant string length limitation and easier to handle CORS issue

**Comment by myangelkamikaze** [comment]
If I remember correctly, postMessage is usually used to communicate with iframes correct? Adding support for that would probably be a good idea in case other tools, especially web based ones, would try to do a similar integration.
In our case, exporting the data import functions to the global namespace is good enough because we have full control of the browser.

**Comment by sinsinpub** [comment]
nope, it's on window context not only iframe. https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
it's suggested safely communicating method between web contexts. otherwise, how does a website expose a 'global namespace' endpoint to a controller of webview? what do you mean exactly for the `console` then?

**Comment by myangelkamikaze** [comment]
When you're using the app and want to reload ship data, you paste the json in 1 and press enter to load it. Assume the function for importing ship data is called "LoadShipData". What I originally meant was just exporting that LoadShipData function to the global namespace, so you can just call it from the browser console (2).

![image](https://user-images.githubusercontent.com/40002167/167743948-053dd2b7-d116-4776-b879-4cc6d66b08f8.png)

**Comment by sinsinpub** [comment]
I see, so you was supposing users of EO74 manually copy & paste json to 1, and manually open devtools console to execute command in 2...?
even you could let the process to be automatic thank to full control of webview, I think it does the same effect if just used `postMessage` in the console instead, and it gives other web apps chance to do so, without control of devtools.

**Comment by myangelkamikaze** [comment]
Yeah, 1 is what's possible now, 2 is what I was requesting. 2 is never meant to be used manually, that wouldn't make any sense since you can do 1. 2 is just meant for automation via custom browsers. In WebView2 you don't need to open the console at all, you can just call [ExecuteScriptAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.executescriptasync?view=webview2-dotnet-1.0.1210.39).

And yeah, after you mentioned postMessage I realized that could also be used for the same purpose, with the advantage that tools that don't have full browser control could use it too.

**Comment by noro6** [comment]
Data import from the browser console is supported.https://github.com/noro6/kc-web/commit/991251838bcef7e14bfbc16f56975ed526cd02f9

```JavaScript
   loadItemData('[{"id":1,"lv":0}]');
   loadShipData('[{"id":1,"lv":1,"st":[0,0,0,0,0,0,0],"exp":[0,100,0]}]');
```

These functions return `true` if the import completed successfully and `false` if something went wrong.
Calling these functions before site initialization is complete will probably return `undefined`.
If you want to prompt for data import without waiting for the site to initialize, consider importing from a `URL fragment`.

**Comment by myangelkamikaze** [comment]
Thank you!

Would the same be possible for fleet data too? If I'm reading it correctly, it would only need loadAndOpenFromDeckBuilder to be added to window, the function itself already works as needed.

**Comment by noro6** [comment]
Oh, I forgot to add😆.https://github.com/noro6/kc-web/commit/6c3821853461054e05afa0475da8aa16ec42f0a1
Thank you. I have added it.

**Comment by myangelkamikaze** [comment]
Thank you!

**Comment by noro6** [comment]
Thank you for your request as well.
Thank you also sinsinpub. It helped me understand.

**Comment by hkuno9000** [comment]
デッキビルダー本家の説明:
http://kancolle-calc.net/deckbuilder.html
> デッキフォーマットは以下の通り：{version: 4, f1: {s1: {id: '100', lv: 40, luck: -1, items:{i1:{id:1, rf: 4, mas:7},{i2:{id:3, rf: 0}}...,ix:{id:43}}}, s2:{}...},...}（2017/2/3更新）

とあるのですが、このIssueの https://github.com/noro6/kc-web/issues/1#issuecomment-1122388266 では
> [https://noro6.github.io/kc-web#import:{"ships":[{"api_ship_id":1,"api_lv":1,"api_kyouka":[0,0,0,0,0,0,0],"api_exp":[0,100,0],"api_slot_ex":0,"api_sally_area":0}],"items":[{"api_slotitem_id":1,"api_level":10}],"predeck":{"version":4,"hqlv":120,"f1":{"s1":{"id":"1","lv":1,"hp":13,"luck":12,"items":{"i1":{"id":1,"mas":0,"rf":1}}}},"a1":{"mode":1,"items":{"i1":{"id":168,"mas":7,"rf":4}}}}}](https://noro6.github.io/kc-web#import:%7B%22ships%22:%5B%7B%22api_ship_id%22:1,%22api_lv%22:1,%22api_kyouka%22:%5B0,0,0,0,0,0,0%5D,%22api_exp%22:%5B0,100,0%5D,%22api_slot_ex%22:0,%22api_sally_area%22:0%7D%5D,%22items%22:%5B%7B%22api_slotitem_id%22:1,%22api_level%22:10%7D%5D,%22predeck%22:%7B%22version%22:4,%22hqlv%22:120,%22f1%22:%7B%22s1%22:%7B%22id%22:%221%22,%22lv%22:1,%22hp%22:13,%22luck%22:12,%22items%22:%7B%22i1%22:%7B%22id%22:1,%22mas%22:0,%22rf%22:1%7D%7D%7D%7D,%22a1%22:%7B%22mode%22:1,%22items%22:%7B%22i1%22:%7B%22id%22:168,%22mas%22:7,%22rf%22:4%7D%7D%7D%7D%7D)

との例示になっており、 predeck.f* に hp フィールドが追加されています。
hp には maxhp を入れるのか nowhp を入れるのかどちらですか？
また、predeck.a* は航空基地の情報と思いますが、各フィールドの説明はどこかにドキュメント化されていますでしょうか？

**Comment by noro6** [comment]
hpはapi_maxhpが適当です。

デッキビルダー本家にないフィールドについてのドキュメントについては申し訳ありませんが存じておりません。
参考までに、弊サイトでは次のフィールドを受け入れ可能です。いずれも改修値を含んだゲーム内表示値です。
```
/** 耐久 */
hp: number;
/** 対潜 */
asw: number;
/** 運 */
luck: number;
```
その他のツールでは、これ以外に火力や雷装など細かい数値を受け入れられるツールもいくらかあるようです。

**Comment by sinsinpub** [comment]
デッキビルダー本家にないものはこっちからの拡張だと思います：
https://github.com/Nishisonic/gkcoi

**Comment by hkuno9000** [comment]
@noro6 @sinsinpub 
情報提供感謝です。基地航空隊の更新タイミングが不完全ですが、実装できました。
https://github.com/hkuno9000/KanColle-YPS/commit/e7b32cc04fef8b8c96c92ff8e58f8169dce43232
