### ISSUE TITLE
Organization loading via url

### ISSUE THREAD

**Issue by myangelkamikaze** [noro6/kc-web#10]
The organization loading has a bug when using the [extended deckbuilder format](https://github.com/Nishisonic/gkcoi#usage). The usage example shows that the values are meant to be total stats, including equipment. But when you generate a link with full stats included, 制空権シミュレータ will add equipment stats on top of the total stats.

[Example ](https://noro6.github.io/kc-web#import:{"predeck":{"version":4,"hqlv":120,"f1":{"name":"大天使神風ちゃん","s1":{"id":476,"lv":180,"exa":true,"items":{"i1":{"id":262,"rf":3},"i2":{"id":439,"rf":0},"i3":{"id":288,"rf":2},"ix":{"id":412,"rf":8}},"hp":29,"fp":44,"tp":77,"aa":49,"ar":38,"asw":180,"ev":138,"los":75,"luck":99,"sp":10,"ra":2}}}})

Expected: 
![image](https://github.com/noro6/kc-web/assets/40002167/92b8fc60-de33-4cba-bf51-7199417dc89d)

Actual: 
![image](https://github.com/noro6/kc-web/assets/40002167/88961e06-c71d-4cb7-95ad-c1d2db020b4b)

Note that this doesn't happen for all stats. The torpedo stat behaves normally, but anti-submarine gets an incorrect value.

**Comment by noro6** [comment]
ご報告ありがとうございました！

**Comment by myangelkamikaze** [comment]
Thanks for the quick fix. 🙏
