### ISSUE TITLE
Data import bug

### ISSUE THREAD

**Issue by myangelkamikaze** [noro6/kc-web#2]
When importing AB data, aircraft positions aren't imported correctly.
Example:
```json
{"version":4,"hqlv":120,"a1":{"items":{"i4":{"id":403,"rf":10,"mas":7}},"mode":1},"a2":{"items":{},"mode":1},"a3":{"items":{},"mode":1}}
```
Expected:
![image](https://user-images.githubusercontent.com/40002167/168275817-b8f97fe0-3f87-4472-857a-3720d4e0b9cf.png)

Actual:
![image](https://user-images.githubusercontent.com/40002167/168275877-f6851e54-e964-46c1-a09c-6bd5625224cf.png)

I checked v1 and it worked correctly there.

**Comment by noro6** [comment]
Thank you for pointing this out.

**Comment by myangelkamikaze** [comment]
Same bug when importing fleets.

Example:
```json
{"version":4,"hqlv":120,"f2":{"s1":{"id":476,"lv":175,"items":{},"luck":99}}}
```

Expected:
![image](https://user-images.githubusercontent.com/40002167/168420770-8236a403-28b5-4684-ad53-6ef8e93d6e3d.png)

Actual:
![image](https://user-images.githubusercontent.com/40002167/168420840-95e8fe01-2691-4f93-acd3-be89481293a8.png)

**Comment by noro6** [comment]
Thank you again for pointing this out.🙇
I have fixed it.

...Very strong Kamikaze!

**Comment by myangelkamikaze** [comment]
Thanks for the quick response!
