### ISSUE TITLE
Deckbuilder format extension

### ISSUE THREAD

**Issue by myangelkamikaze** [noro6/kc-web#5]
We recently extended the deckbuilder format in 74EO to match [gkcoi](https://github.com/Nishisonic/gkcoi#deckbuilder) (excluding properties that are used as application settings).

I now noticed that this breaks the data import in air control simulator, because it enumerates all properties in fleet, assuming it's always a ship, which breaks with the fleet name property, which is just a string.

![image](https://user-images.githubusercontent.com/40002167/186577132-c1dead8a-b4cf-47fb-9877-8acdab488cd1.png)

Do you have any plans to support the gkcoi extended format, or should we use the old basic format for fleet export?

**Comment by noro6** [comment]
The problem has been fixed.https://github.com/noro6/kc-web/commit/a729c3b530f2b50722b834eb655c8299564d4d89
Thank you for your report🙇‍♂️

**Comment by myangelkamikaze** [comment]
Thank you for the fix. 🙏 🙏 🙏 🙏 🙏
