### ISSUE TITLE
Odd behavior when using link with data import

### ISSUE THREAD

**Issue by myangelkamikaze** [noro6/kc-web#7]
When opening the air control simulator using a link that contains data (example: https://github.com/noro6/kc-web/issues/1#issuecomment-1122388266), the application opens with 2 tabs. The first tab contains the expected data, the second tab is empty. Both tabs are also selected.

![image](https://user-images.githubusercontent.com/40002167/197951974-d836b311-503e-40a2-84f4-b0ae952a00d0.png)

Expected behavior: only the first tab should exist.

**Comment by noro6** [comment]
Thank you for the report!

**Comment by myangelkamikaze** [comment]
Thanks for the fix!
