### ISSUE TITLE
文字がすごく見つらい、以前のフォントの戻すオプションをください

### ISSUE THREAD

**Issue by RadarNyan** [noro6/kc-web#9]
![image](https://github.com/noro6/kc-web/assets/2091529/3e105bae-b3df-43cf-a451-be53e5519e8f)
（上半分は今までの文字表現、下半分は現在）

Noto Sans の ClearType 対応（ヒンティング情報）は不十分ので、Windows 標準スケール（100% dpi）の環境か小文字がすごく見つらい、全体的にもやもやで目が疲れる。Noto Sans を使わないオプション（すなわち以前のようにシステムフォントを使う）をください。

**Comment by noro6** [comment]
ご連絡ありがとうございます。
イベントが間近であるため、差し戻しという形で対応いたしました。

オプション機能を含め今後、何かいい方法がないか模索してみます。

**Comment by RadarNyan** [comment]
イベント前に対応してくれで、ありがどうございます。

高画素密度（HiDPI）のモニターではどんなフォントの文字も綺麗に表示できますが、自分はいまだに１００％スケーリングのモニター（27型1440p）を使ってます。UIなど小さい文字を使う場合、ClearType 完全対応のフォント（Windows デフォルトフォント「メイリオ」）、あるいはドットで文字を描くビットマップフォント以外のフォントを使うと可読性が大幅に落ちます。

Noto Sans を使いたい場合、オプションでオフにできるように、あるいは[一定以上のスケーリング設定した場合のみ適用するように](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution)した方が無難だと思います。
